- name: Research cloud Co plugin
  hosts: all
  gather_facts: false

  tasks:
    - name: Wait for system to become reachable
      wait_for_connection:
        timeout: 300

    - name: Creates directory
      ansible.builtin.file:
        path: test_test
        state: directory
