- name: Research cloud Co plugin
  hosts: all
  gather_facts: false

  tasks:
    - name: Wait for system to become reachable
      wait_for_connection:
        timeout: 300

    - name: install rye
      ansible.builtin.shell: curl -sSf https://rye.astral.sh/get | RYE_TOOLCHAIN_VERSION="3.11.9" RYE_INSTALL_OPTION="--yes" bash